# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - george-edison55-precise-backports
  packages:
   - gcc-5
   - g++-5
   - cmake
   - cmake-data
before_install:
 # c++11
 #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 # boost 1.55
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -y libboost-chrono1.55-dev libboost-random1.55-dev libboost-regex1.55-dev libboost-system1.55-dev libboost-thread1.55-dev libboost-test1.55-dev

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - sudo lsb_release -a
  - gcc --version
  - g++ --version
  - cmake --version
  - mkdir build 
  - cd build 
  - cmake  -DCMAKE_BUILD_TYPE=Debug .. 
  - cmake --build .

branches:
  only:
    - master
    - develop

notifications:
  recipients:
    - gaoxiaojun@gmail.com 
  email:
    on_success: change
    on_failure: always
